[package]
name = "wheel-derive"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Derive macros for the wheel crate."

[lib]
proc-macro = true

[dependencies]
itertools = "0.14"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
